(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/wcce/wcce-tabbar"],{"1be8":function(t,n,e){"use strict";e.r(n);var i=e("aa12"),a=e.n(i);for(var o in i)["default"].indexOf(o)<0&&function(t){e.d(n,t,(function(){return i[t]}))}(o);n["default"]=a.a},"54b8":function(t,n,e){"use strict";e.d(n,"b",(function(){return i})),e.d(n,"c",(function(){return a})),e.d(n,"a",(function(){}));var i=function(){var t=this,n=t.$createElement,e=(t._self._c,t.tabbar?t.__map(t.tabbar.list,(function(n,e){var i=t.__get_orig(n),a=n.linkValue.indexOf(t.current),o=n.linkValue.indexOf(t.current),r=n.linkValue.indexOf(t.current);return{$orig:i,g0:a,g1:o,g2:r}})):null);t.$mp.data=Object.assign({},{$root:{l0:e}})},a=[]},7639:function(t,n,e){"use strict";var i=e("7a91"),a=e.n(i);a.a},"7a91":function(t,n,e){},aa12:function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e={name:"wccetabbar",props:{current:{type:String,default:"tabbar/home"}},data:function(){return{config:null,tabbar:null}},mounted:function(){var t=this;setTimeout((function(){t.config=t.$db.get("config"),t.tabbar=t.config.tabbar}),350)},methods:{handleClick:function(n,e,i){if(this.currentIndex=n,i)if(1==e){if(-1==i.indexOf("http"))return i.indexOf("tabbar")>-1?void t.switchTab({url:i}):void this.$common.navigateTo(i);this.$common.navigateTo("/pages/outside/index?url="+encodeURIComponent(i))}else{if(2==e)return void(i.indexOf("|")>-1&&this.$common.goviewTo(i.split("|")[1],i.split("|")[0]));if(3==e)this.$common.navigateTo("/pages/resource/index?id="+i);else if(4==e)this.$common.navigateTo("/pages/article/show?id="+i);else if(5==e)this.$common.navigateTo("/pages/article/list?sort_id="+i);else{if(6==e)return i.indexOf("tabbar")>-1?void t.switchTab({url:i}):void this.$common.navigateTo(i);if(!(i.indexOf("@")>-1))return void this.$common.navigateTo(i);var a=i.split("@");t.navigateToMiniProgram({appId:a[0],path:a[1]})}}}}};n.default=e}).call(this,e("df3c")["default"])},d070:function(t,n,e){"use strict";e.r(n);var i=e("54b8"),a=e("1be8");for(var o in a)["default"].indexOf(o)<0&&function(t){e.d(n,t,(function(){return a[t]}))}(o);e("7639");var r=e("828b"),u=Object(r["a"])(a["default"],i["b"],i["c"],!1,null,null,null,!1,i["a"],void 0);n["default"]=u.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/wcce/wcce-tabbar-create-component',
    {
        'components/wcce/wcce-tabbar-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("d070"))
        })
    },
    [['components/wcce/wcce-tabbar-create-component']]
]);
