(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["uni_modules/uv-badge/components/uv-badge/uv-badge"],{"21e2":function(t,e,u){"use strict";u.r(e);var a=u("60bf"),i=u.n(a);for(var r in a)["default"].indexOf(r)<0&&function(t){u.d(e,t,(function(){return a[t]}))}(r);e["default"]=i.a},"320a":function(t,e,u){"use strict";u.r(e);var a=u("b0ef"),i=u("21e2");for(var r in i)["default"].indexOf(r)<0&&function(t){u.d(e,t,(function(){return i[t]}))}(r);u("6dd8");var n=u("828b"),o=Object(n["a"])(i["default"],a["b"],a["c"],!1,null,"33d90208",null,!1,a["a"],void 0);e["default"]=o.exports},"4a91":function(t,e,u){},"60bf":function(t,e,u){"use strict";var a=u("47a9");Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var i=a(u("7110")),r=a(u("f243")),n=a(u("95e7")),o={name:"uv-badge",mixins:[i.default,r.default,n.default],computed:{boxStyle:function(){return{}},badgeStyle:function(){var t={};if(this.color&&(t.color=this.color),this.bgColor&&!this.inverted&&(t.backgroundColor=this.bgColor),this.absolute&&(t.position="absolute",this.offset.length)){var e=this.offset[0],u=this.offset[1]||e;t.top=this.$uv.addUnit(e),t.right=this.$uv.addUnit(u)}return t},showValue:function(){switch(this.numberType){case"overflow":return Number(this.value)>Number(this.max)?this.max+"+":this.value;case"ellipsis":return Number(this.value)>Number(this.max)?"...":this.value;case"limit":return Number(this.value)>999?Number(this.value)>=9999?Math.floor(this.value/1e4*100)/100+"w":Math.floor(this.value/1e3*100)/100+"k":this.value;default:return Number(this.value)}},propsType:function(){return this.type||"error"}}};e.default=o},"6dd8":function(t,e,u){"use strict";var a=u("4a91"),i=u.n(a);i.a},b0ef:function(t,e,u){"use strict";u.d(e,"b",(function(){return a})),u.d(e,"c",(function(){return i})),u.d(e,"a",(function(){}));var a=function(){var t=this,e=t.$createElement,u=(t._self._c,t.show&&(0!==Number(t.value)||t.showZero||t.isDot)),a=u?t.__get_style([t.$uv.addStyle(t.customStyle),t.badgeStyle]):null;t.$mp.data=Object.assign({},{$root:{m0:u,s0:a}})},i=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'uni_modules/uv-badge/components/uv-badge/uv-badge-create-component',
    {
        'uni_modules/uv-badge/components/uv-badge/uv-badge-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("320a"))
        })
    },
    [['uni_modules/uv-badge/components/uv-badge/uv-badge-create-component']]
]);
